namespace WeaverAnnotations.InlineIL.Gen
{
	public abstract class GenArg {}
    public class _T0 : GenArg {}
    public class _M0 : GenArg {}
    public class _T1 : GenArg {}
    public class _M1 : GenArg {}
    public class _T2 : GenArg {}
    public class _M2 : GenArg {}
    public class _T3 : GenArg {}
    public class _M3 : GenArg {}
    public class _T4 : GenArg {}
    public class _M4 : GenArg {}
    public class _T5 : GenArg {}
    public class _M5 : GenArg {}
    public class _T6 : GenArg {}
    public class _M6 : GenArg {}
    public class _T7 : GenArg {}
    public class _M7 : GenArg {}
    public class _T8 : GenArg {}
    public class _M8 : GenArg {}
    public class _T9 : GenArg {}
    public class _M9 : GenArg {}
    public class _T10 : GenArg {}
    public class _M10 : GenArg {}
    public class _T11 : GenArg {}
    public class _M11 : GenArg {}
    public class _T12 : GenArg {}
    public class _M12 : GenArg {}
    public class _T13 : GenArg {}
    public class _M13 : GenArg {}
    public class _T14 : GenArg {}
    public class _M14 : GenArg {}
    public class _T15 : GenArg {}
    public class _M15 : GenArg {}
    public class _T16 : GenArg {}
    public class _M16 : GenArg {}
    public class _T17 : GenArg {}
    public class _M17 : GenArg {}
    public class _T18 : GenArg {}
    public class _M18 : GenArg {}
    public class _T19 : GenArg {}
    public class _M19 : GenArg {}
    public class _T20 : GenArg {}
    public class _M20 : GenArg {}
    public class _T21 : GenArg {}
    public class _M21 : GenArg {}
    public class _T22 : GenArg {}
    public class _M22 : GenArg {}
    public class _T23 : GenArg {}
    public class _M23 : GenArg {}
    public class _T24 : GenArg {}
    public class _M24 : GenArg {}
    public class _T25 : GenArg {}
    public class _M25 : GenArg {}
    public class _T26 : GenArg {}
    public class _M26 : GenArg {}
    public class _T27 : GenArg {}
    public class _M27 : GenArg {}
    public class _T28 : GenArg {}
    public class _M28 : GenArg {}
    public class _T29 : GenArg {}
    public class _M29 : GenArg {}
    public class _T30 : GenArg {}
    public class _M30 : GenArg {}
    public class _T31 : GenArg {}
    public class _M31 : GenArg {}
    public class _T32 : GenArg {}
    public class _M32 : GenArg {}
    public class _T33 : GenArg {}
    public class _M33 : GenArg {}
    public class _T34 : GenArg {}
    public class _M34 : GenArg {}
    public class _T35 : GenArg {}
    public class _M35 : GenArg {}
    public class _T36 : GenArg {}
    public class _M36 : GenArg {}
    public class _T37 : GenArg {}
    public class _M37 : GenArg {}
    public class _T38 : GenArg {}
    public class _M38 : GenArg {}
    public class _T39 : GenArg {}
    public class _M39 : GenArg {}
    public class _T40 : GenArg {}
    public class _M40 : GenArg {}
    public class _T41 : GenArg {}
    public class _M41 : GenArg {}
    public class _T42 : GenArg {}
    public class _M42 : GenArg {}
    public class _T43 : GenArg {}
    public class _M43 : GenArg {}
    public class _T44 : GenArg {}
    public class _M44 : GenArg {}
    public class _T45 : GenArg {}
    public class _M45 : GenArg {}
    public class _T46 : GenArg {}
    public class _M46 : GenArg {}
    public class _T47 : GenArg {}
    public class _M47 : GenArg {}
    public class _T48 : GenArg {}
    public class _M48 : GenArg {}
    public class _T49 : GenArg {}
    public class _M49 : GenArg {}
    public class _T50 : GenArg {}
    public class _M50 : GenArg {}
    public class _T51 : GenArg {}
    public class _M51 : GenArg {}
    public class _T52 : GenArg {}
    public class _M52 : GenArg {}
    public class _T53 : GenArg {}
    public class _M53 : GenArg {}
    public class _T54 : GenArg {}
    public class _M54 : GenArg {}
    public class _T55 : GenArg {}
    public class _M55 : GenArg {}
    public class _T56 : GenArg {}
    public class _M56 : GenArg {}
    public class _T57 : GenArg {}
    public class _M57 : GenArg {}
    public class _T58 : GenArg {}
    public class _M58 : GenArg {}
    public class _T59 : GenArg {}
    public class _M59 : GenArg {}
    public class _T60 : GenArg {}
    public class _M60 : GenArg {}
    public class _T61 : GenArg {}
    public class _M61 : GenArg {}
    public class _T62 : GenArg {}
    public class _M62 : GenArg {}
    public class _T63 : GenArg {}
    public class _M63 : GenArg {}
    public class _T64 : GenArg {}
    public class _M64 : GenArg {}
    public class _T65 : GenArg {}
    public class _M65 : GenArg {}
    public class _T66 : GenArg {}
    public class _M66 : GenArg {}
    public class _T67 : GenArg {}
    public class _M67 : GenArg {}
    public class _T68 : GenArg {}
    public class _M68 : GenArg {}
    public class _T69 : GenArg {}
    public class _M69 : GenArg {}
    public class _T70 : GenArg {}
    public class _M70 : GenArg {}
    public class _T71 : GenArg {}
    public class _M71 : GenArg {}
    public class _T72 : GenArg {}
    public class _M72 : GenArg {}
    public class _T73 : GenArg {}
    public class _M73 : GenArg {}
    public class _T74 : GenArg {}
    public class _M74 : GenArg {}
    public class _T75 : GenArg {}
    public class _M75 : GenArg {}
    public class _T76 : GenArg {}
    public class _M76 : GenArg {}
    public class _T77 : GenArg {}
    public class _M77 : GenArg {}
    public class _T78 : GenArg {}
    public class _M78 : GenArg {}
    public class _T79 : GenArg {}
    public class _M79 : GenArg {}
    public class _T80 : GenArg {}
    public class _M80 : GenArg {}
    public class _T81 : GenArg {}
    public class _M81 : GenArg {}
    public class _T82 : GenArg {}
    public class _M82 : GenArg {}
    public class _T83 : GenArg {}
    public class _M83 : GenArg {}
    public class _T84 : GenArg {}
    public class _M84 : GenArg {}
    public class _T85 : GenArg {}
    public class _M85 : GenArg {}
    public class _T86 : GenArg {}
    public class _M86 : GenArg {}
    public class _T87 : GenArg {}
    public class _M87 : GenArg {}
    public class _T88 : GenArg {}
    public class _M88 : GenArg {}
    public class _T89 : GenArg {}
    public class _M89 : GenArg {}
    public class _T90 : GenArg {}
    public class _M90 : GenArg {}
    public class _T91 : GenArg {}
    public class _M91 : GenArg {}
    public class _T92 : GenArg {}
    public class _M92 : GenArg {}
    public class _T93 : GenArg {}
    public class _M93 : GenArg {}
    public class _T94 : GenArg {}
    public class _M94 : GenArg {}
    public class _T95 : GenArg {}
    public class _M95 : GenArg {}
    public class _T96 : GenArg {}
    public class _M96 : GenArg {}
    public class _T97 : GenArg {}
    public class _M97 : GenArg {}
    public class _T98 : GenArg {}
    public class _M98 : GenArg {}
    public class _T99 : GenArg {}
    public class _M99 : GenArg {}
    public class _T100 : GenArg {}
    public class _M100 : GenArg {}
    public class _T101 : GenArg {}
    public class _M101 : GenArg {}
    public class _T102 : GenArg {}
    public class _M102 : GenArg {}
    public class _T103 : GenArg {}
    public class _M103 : GenArg {}
    public class _T104 : GenArg {}
    public class _M104 : GenArg {}
    public class _T105 : GenArg {}
    public class _M105 : GenArg {}
    public class _T106 : GenArg {}
    public class _M106 : GenArg {}
    public class _T107 : GenArg {}
    public class _M107 : GenArg {}
    public class _T108 : GenArg {}
    public class _M108 : GenArg {}
    public class _T109 : GenArg {}
    public class _M109 : GenArg {}
    public class _T110 : GenArg {}
    public class _M110 : GenArg {}
    public class _T111 : GenArg {}
    public class _M111 : GenArg {}
    public class _T112 : GenArg {}
    public class _M112 : GenArg {}
    public class _T113 : GenArg {}
    public class _M113 : GenArg {}
    public class _T114 : GenArg {}
    public class _M114 : GenArg {}
    public class _T115 : GenArg {}
    public class _M115 : GenArg {}
    public class _T116 : GenArg {}
    public class _M116 : GenArg {}
    public class _T117 : GenArg {}
    public class _M117 : GenArg {}
    public class _T118 : GenArg {}
    public class _M118 : GenArg {}
    public class _T119 : GenArg {}
    public class _M119 : GenArg {}
    public class _T120 : GenArg {}
    public class _M120 : GenArg {}
    public class _T121 : GenArg {}
    public class _M121 : GenArg {}
    public class _T122 : GenArg {}
    public class _M122 : GenArg {}
    public class _T123 : GenArg {}
    public class _M123 : GenArg {}
    public class _T124 : GenArg {}
    public class _M124 : GenArg {}
    public class _T125 : GenArg {}
    public class _M125 : GenArg {}
    public class _T126 : GenArg {}
    public class _M126 : GenArg {}
    public class _T127 : GenArg {}
    public class _M127 : GenArg {}
    public class _T128 : GenArg {}
    public class _M128 : GenArg {}
    public class _T129 : GenArg {}
    public class _M129 : GenArg {}
    public class _T130 : GenArg {}
    public class _M130 : GenArg {}
    public class _T131 : GenArg {}
    public class _M131 : GenArg {}
    public class _T132 : GenArg {}
    public class _M132 : GenArg {}
    public class _T133 : GenArg {}
    public class _M133 : GenArg {}
    public class _T134 : GenArg {}
    public class _M134 : GenArg {}
    public class _T135 : GenArg {}
    public class _M135 : GenArg {}
    public class _T136 : GenArg {}
    public class _M136 : GenArg {}
    public class _T137 : GenArg {}
    public class _M137 : GenArg {}
    public class _T138 : GenArg {}
    public class _M138 : GenArg {}
    public class _T139 : GenArg {}
    public class _M139 : GenArg {}
    public class _T140 : GenArg {}
    public class _M140 : GenArg {}
    public class _T141 : GenArg {}
    public class _M141 : GenArg {}
    public class _T142 : GenArg {}
    public class _M142 : GenArg {}
    public class _T143 : GenArg {}
    public class _M143 : GenArg {}
    public class _T144 : GenArg {}
    public class _M144 : GenArg {}
    public class _T145 : GenArg {}
    public class _M145 : GenArg {}
    public class _T146 : GenArg {}
    public class _M146 : GenArg {}
    public class _T147 : GenArg {}
    public class _M147 : GenArg {}
    public class _T148 : GenArg {}
    public class _M148 : GenArg {}
    public class _T149 : GenArg {}
    public class _M149 : GenArg {}
    public class _T150 : GenArg {}
    public class _M150 : GenArg {}
    public class _T151 : GenArg {}
    public class _M151 : GenArg {}
    public class _T152 : GenArg {}
    public class _M152 : GenArg {}
    public class _T153 : GenArg {}
    public class _M153 : GenArg {}
    public class _T154 : GenArg {}
    public class _M154 : GenArg {}
    public class _T155 : GenArg {}
    public class _M155 : GenArg {}
    public class _T156 : GenArg {}
    public class _M156 : GenArg {}
    public class _T157 : GenArg {}
    public class _M157 : GenArg {}
    public class _T158 : GenArg {}
    public class _M158 : GenArg {}
    public class _T159 : GenArg {}
    public class _M159 : GenArg {}
    public class _T160 : GenArg {}
    public class _M160 : GenArg {}
    public class _T161 : GenArg {}
    public class _M161 : GenArg {}
    public class _T162 : GenArg {}
    public class _M162 : GenArg {}
    public class _T163 : GenArg {}
    public class _M163 : GenArg {}
    public class _T164 : GenArg {}
    public class _M164 : GenArg {}
    public class _T165 : GenArg {}
    public class _M165 : GenArg {}
    public class _T166 : GenArg {}
    public class _M166 : GenArg {}
    public class _T167 : GenArg {}
    public class _M167 : GenArg {}
    public class _T168 : GenArg {}
    public class _M168 : GenArg {}
    public class _T169 : GenArg {}
    public class _M169 : GenArg {}
    public class _T170 : GenArg {}
    public class _M170 : GenArg {}
    public class _T171 : GenArg {}
    public class _M171 : GenArg {}
    public class _T172 : GenArg {}
    public class _M172 : GenArg {}
    public class _T173 : GenArg {}
    public class _M173 : GenArg {}
    public class _T174 : GenArg {}
    public class _M174 : GenArg {}
    public class _T175 : GenArg {}
    public class _M175 : GenArg {}
    public class _T176 : GenArg {}
    public class _M176 : GenArg {}
    public class _T177 : GenArg {}
    public class _M177 : GenArg {}
    public class _T178 : GenArg {}
    public class _M178 : GenArg {}
    public class _T179 : GenArg {}
    public class _M179 : GenArg {}
    public class _T180 : GenArg {}
    public class _M180 : GenArg {}
    public class _T181 : GenArg {}
    public class _M181 : GenArg {}
    public class _T182 : GenArg {}
    public class _M182 : GenArg {}
    public class _T183 : GenArg {}
    public class _M183 : GenArg {}
    public class _T184 : GenArg {}
    public class _M184 : GenArg {}
    public class _T185 : GenArg {}
    public class _M185 : GenArg {}
    public class _T186 : GenArg {}
    public class _M186 : GenArg {}
    public class _T187 : GenArg {}
    public class _M187 : GenArg {}
    public class _T188 : GenArg {}
    public class _M188 : GenArg {}
    public class _T189 : GenArg {}
    public class _M189 : GenArg {}
    public class _T190 : GenArg {}
    public class _M190 : GenArg {}
    public class _T191 : GenArg {}
    public class _M191 : GenArg {}
    public class _T192 : GenArg {}
    public class _M192 : GenArg {}
    public class _T193 : GenArg {}
    public class _M193 : GenArg {}
    public class _T194 : GenArg {}
    public class _M194 : GenArg {}
    public class _T195 : GenArg {}
    public class _M195 : GenArg {}
    public class _T196 : GenArg {}
    public class _M196 : GenArg {}
    public class _T197 : GenArg {}
    public class _M197 : GenArg {}
    public class _T198 : GenArg {}
    public class _M198 : GenArg {}
    public class _T199 : GenArg {}
    public class _M199 : GenArg {}
    public class _T200 : GenArg {}
    public class _M200 : GenArg {}
    public class _T201 : GenArg {}
    public class _M201 : GenArg {}
    public class _T202 : GenArg {}
    public class _M202 : GenArg {}
    public class _T203 : GenArg {}
    public class _M203 : GenArg {}
    public class _T204 : GenArg {}
    public class _M204 : GenArg {}
    public class _T205 : GenArg {}
    public class _M205 : GenArg {}
    public class _T206 : GenArg {}
    public class _M206 : GenArg {}
    public class _T207 : GenArg {}
    public class _M207 : GenArg {}
    public class _T208 : GenArg {}
    public class _M208 : GenArg {}
    public class _T209 : GenArg {}
    public class _M209 : GenArg {}
    public class _T210 : GenArg {}
    public class _M210 : GenArg {}
    public class _T211 : GenArg {}
    public class _M211 : GenArg {}
    public class _T212 : GenArg {}
    public class _M212 : GenArg {}
    public class _T213 : GenArg {}
    public class _M213 : GenArg {}
    public class _T214 : GenArg {}
    public class _M214 : GenArg {}
    public class _T215 : GenArg {}
    public class _M215 : GenArg {}
    public class _T216 : GenArg {}
    public class _M216 : GenArg {}
    public class _T217 : GenArg {}
    public class _M217 : GenArg {}
    public class _T218 : GenArg {}
    public class _M218 : GenArg {}
    public class _T219 : GenArg {}
    public class _M219 : GenArg {}
    public class _T220 : GenArg {}
    public class _M220 : GenArg {}
    public class _T221 : GenArg {}
    public class _M221 : GenArg {}
    public class _T222 : GenArg {}
    public class _M222 : GenArg {}
    public class _T223 : GenArg {}
    public class _M223 : GenArg {}
    public class _T224 : GenArg {}
    public class _M224 : GenArg {}
    public class _T225 : GenArg {}
    public class _M225 : GenArg {}
    public class _T226 : GenArg {}
    public class _M226 : GenArg {}
    public class _T227 : GenArg {}
    public class _M227 : GenArg {}
    public class _T228 : GenArg {}
    public class _M228 : GenArg {}
    public class _T229 : GenArg {}
    public class _M229 : GenArg {}
    public class _T230 : GenArg {}
    public class _M230 : GenArg {}
    public class _T231 : GenArg {}
    public class _M231 : GenArg {}
    public class _T232 : GenArg {}
    public class _M232 : GenArg {}
    public class _T233 : GenArg {}
    public class _M233 : GenArg {}
    public class _T234 : GenArg {}
    public class _M234 : GenArg {}
    public class _T235 : GenArg {}
    public class _M235 : GenArg {}
    public class _T236 : GenArg {}
    public class _M236 : GenArg {}
    public class _T237 : GenArg {}
    public class _M237 : GenArg {}
    public class _T238 : GenArg {}
    public class _M238 : GenArg {}
    public class _T239 : GenArg {}
    public class _M239 : GenArg {}
    public class _T240 : GenArg {}
    public class _M240 : GenArg {}
    public class _T241 : GenArg {}
    public class _M241 : GenArg {}
    public class _T242 : GenArg {}
    public class _M242 : GenArg {}
    public class _T243 : GenArg {}
    public class _M243 : GenArg {}
    public class _T244 : GenArg {}
    public class _M244 : GenArg {}
    public class _T245 : GenArg {}
    public class _M245 : GenArg {}
    public class _T246 : GenArg {}
    public class _M246 : GenArg {}
    public class _T247 : GenArg {}
    public class _M247 : GenArg {}
    public class _T248 : GenArg {}
    public class _M248 : GenArg {}
    public class _T249 : GenArg {}
    public class _M249 : GenArg {}
    public class _T250 : GenArg {}
    public class _M250 : GenArg {}
    public class _T251 : GenArg {}
    public class _M251 : GenArg {}
    public class _T252 : GenArg {}
    public class _M252 : GenArg {}
    public class _T253 : GenArg {}
    public class _M253 : GenArg {}
    public class _T254 : GenArg {}
    public class _M254 : GenArg {}
    public class _T255 : GenArg {}
    public class _M255 : GenArg {}

}